### ISSUE TITLE
DB engine returns the latest version for every FullDataset checkout

### ISSUE THREAD

**Issue by maqzi** [VIDA-NYU/openclean-core#107] opened 2021-02-15 06:29 UTC
**Describe the bug**
When using the openclean engine to maintain provenance, committing and checking out works correctly for DataSample objects, however for FullDataset objects, checking out a version always returns the latest dataset version.

**To Reproduce**
1. Create a new `openclean.engine.base.DB` instance.
2. Use `db.create(*)` to add a new dataset to the engine.
3. Use `db.commit(*)` to commit the first version.
4. Make changes to the dataset.
5. Use `db.commit(*)` to commit the changes.
6. Look at the snapshots using `db.dataset(*).log()` to get the operation identifier for the first commit.
7. Use `db.dataset(*).checkout(*)` to checkout the first version.
8. The latest version is returned.

*- denotes missing arguments

**Expected behavior**
The respective dataset version should be returned.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python: 3.7.4

**Comment by heikomuller** [comment] 2021-02-16 13:20
I think the problem is here:

https://github.com/VIDA-NYU/openclean-core/blob/a16bc80224dfaa70ba9df17113972d124f9b2056/openclean/engine/log.py#L88

When creating the `OperationLog` from a given list of snapshots the `LogEntry` does not receive the version number for the snapshot. Thus, when an attempt is made to checkout the dataset for a given log entry the associated version number is None and by the default the last version in the dataset history is returned.

**Comment by heikomuller** [comment] 2021-02-16 13:27
We could also get rid of the distinction between `identifier` and `version` number and only keep the version information. The distinction was made to be able to combine snapshots from full datasets and sample datasets in the same log. As discussed previously, we are not going to display such a mixed history in the UI recipe which means that there is no need to have both attributes.

**Comment by heikomuller** [comment] 2021-02-16 21:50
Similar to my previous comment, we can also get rid of the `is_committed` property of the `LogEntry`. In a sample dataset all log entries are un-committed and in a full dataset all log entries will be committed.

**Comment by maqzi** [comment] 2021-02-17 05:17
Agreed. The distinction between `version` and `identifier` was redundant unless we wanted to display them on the UI. I removed it and the `is_committed` property.

**Closed** 2021-02-17 18:31 UTC
